name: Deploy to Azure Web App

env:
  AZURE_WEBAPP_NAME: aubcovax
  AZURE_RESOURCE_GROUP: aubcovax_backend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: install texlive-latex-base
        run: sudo apt-get install texlive-latex-base
        
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

